pub const CRATE_UPDATE_DATE: &str = "2023-04-28";
pub const CRATE_REPOSITORY: &str = "https://github.com/shellrow/nesmap";
pub const PACKAGE_DIR_NAME: &str = "packages";
pub const PRESOURCE_DIR_NAME: &str = "resources";
pub const DB_NAME: &str = "nmdb.db";
#[cfg(not(target_os = "macos"))]
pub const PACKAGE_NAME_NESMAP: &str = "nesmap";
#[cfg(target_os = "macos")]
pub const PACKAGE_NAME_NESMAP: &str = "nesmap.app";
#[cfg(not(target_os = "macos"))]
pub const PACKAGE_NAME_NESMAP_DESKTOP: &str = "nesmap-desktop";
#[cfg(target_os = "macos")]
pub const PACKAGE_NAME_NESMAP_DESKTOP: &str = "nesmap-desktop.app";
#[cfg(not(target_os = "windows"))]
pub const APP_NAME_NESMAP: &str = "nesmap";
#[cfg(target_os = "windows")]
pub const APP_NAME_NESMAP: &str = "nesmap.exe";
// #[cfg(not(target_os = "windows"))]
// pub const APP_NAME_NESMAP_DESKTOP: &str = "nesmap-desktop";
// #[cfg(target_os = "windows")]
// pub const APP_NAME_NESMAP_DESKTOP: &str = "nesmap-desktop.exe";
