[package]
name = "nesmap"
version = "0.1.0"
edition = "2021"
authors = ["shellrow <shellrow@protonmail.com>"]
description = "Cross-platform network mapper"
repository = "https://github.com/shellrow/nesmap"
readme = "README.md"
keywords = ["network","security","scan","cli","cross-platform"]
categories = ["network-programming"]
license = "MIT"

[[bin]]
name = "nesmap"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
default-net = "0.14.1"
clap = { version = "3.1", features = ["cargo"] }
indicatif = "0.16.2"
term-table = "1.3.2"
async-io = "1.6"
chrono = "0.4"
dns-lookup = "1.0"
sudo = "0.6"
runas = "1.0.0"
regex = "1.6.0"
pnet_packet = "0.31.0"
pnet_datalink = "0.31.0"
ipnet = "2.5.0"
netscan = { version = "0.13.0", features = ["full"] }
domainscan = "0.2.0"
tracert = "0.4.1"
tokio = "1.0"
