[package]
name = "netprobe-cli"
version = "0.6.0"
edition = "2021"
authors = ["shellrow <shellrow@protonmail.com>"]
description = "Moved. Placeholder for netprobe-cli."
readme = "README.md"
license = "MIT"

[dependencies]
