[package]
name = "cross-socket-deps"
version = "0.1.0"
edition = "2021"
authors = ["shellrow <shellrow@protonmail.com>"]
description = "cross-socket-deps is a helper crate for the cross-socket library, managing OS-specific dependencies to ensure seamless cross-platform functionality"
repository = "https://github.com/shellrow/cross-socket"
readme = "README.md"
keywords = ["network", "packet"]
categories = ["network-programming"]
license = "MIT"

[dependencies]
privilege = "0.3"
sha2 = "0.10"
reqwest = { version = "0.11", features = ["blocking"] }
inquire = "0.6"
home = "0.5"
zip = "0.6"

[target.'cfg(windows)'.dependencies]
winreg = "0.50"
